name: Flujo para ejecutar secuencialmente las tareas de construcción, prueba y publicación
on:
  push:  
    branches: [manmanher]
  pull_request:
    branches: [manmanher]
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo (solo el .jar) el código
        run: |
          chmod +x gradlew        
          ./gradlew assemble
      - name: Mensaje por pantalla con mi uvus
        run: |
          echo "${{ github.actor}}"
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Ejecutando tests
        run: |
          chmod +x gradlew        
          ./gradlew test
      - name: Mensaje por pantalla con mi uvus
        run: |
          echo "${{ github.actor}}"
          
  Publish:
    runs-on: ubuntu-latest
    needs: Test
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo y publicando el paquete
        run: |
          chmod +x gradlew
          ./gradlew publish
      - name: Mensaje por pantalla con mi uvus
        run: |
          echo "${{ github.actor}}"
